name: Beatnik A.I.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          # textract dependencies:
          sudo apt-get update
          sudo apt-get install python-dev-is-python3 libxml2-dev libxslt1-dev antiword unrtf poppler-utils pstotext tesseract-ocr flac ffmpeg lame libmad0 libsox-fmt-mp3 sox libjpeg-dev swig libpulse-dev
          cd src/
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install Playwright dependencies
        run: playwright install
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      # - name: Test with pytest
      #   run: |
      #     pytest
      - name: Deploy to modal labs
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_DEPLOY_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_DEPLOY_TOKEN_SECRET }}
        run: |
          # if all tests pass until this point, deploy the script to modal
          cd src/ 
          modal token set --token-id $MODAL_TOKEN_ID --token-secret $MODAL_TOKEN_SECRET
          modal deploy main.py
